class CommonMessage:
    # Audio related
    AUDIO_NOT_FOUND = "AUDIO_NOT_FOUND"
    AUDIO_NOT_TRANSCRIBED = "AUDIO_NOT_TRANSCRIBED"
    AUDIO_FILE_TOO_LARGE = "AUDIO_FILE_TOO_LARGE"
    AUDIO_FILE_INVALID_FORMAT = "AUDIO_FILE_INVALID_FORMAT"
    AUDIO_FILE_SAVE_FAILED = "AUDIO_FILE_SAVE_FAILED"
    AUDIO_FILE_NOT_FOUND_ON_DISK = "AUDIO_FILE_NOT_FOUND_ON_DISK"
    AUDIO_UPLOADED_SUCCESS = "AUDIO_UPLOADED_SUCCESS"
    AUDIO_DELETED_SUCCESS = "AUDIO_DELETED_SUCCESS"
    AUDIO_RETRIEVED_SUCCESS = "AUDIO_RETRIEVED_SUCCESS"
    AUDIO_LIST_RETRIEVED_SUCCESS = "AUDIO_LIST_RETRIEVED_SUCCESS"
    AUDIO_UPDATED_SUCCESS = "AUDIO_UPDATED_SUCCESS"
    AUDIO_UPDATE_NO_FIELDS = "AUDIO_UPDATE_NO_FIELDS"
    
    # Note related
    NOTE_NOT_FOUND = "NOTE_NOT_FOUND"
    NOTE_CREATE_FAILED = "NOTE_CREATE_FAILED"
    NOTE_UPDATE_FAILED = "NOTE_UPDATE_FAILED"
    NOTE_DELETE_FAILED = "NOTE_DELETE_FAILED"
    NOTE_CREATED_SUCCESS = "NOTE_CREATED_SUCCESS"
    NOTE_UPDATED_SUCCESS = "NOTE_UPDATED_SUCCESS"
    NOTE_DELETED_SUCCESS = "NOTE_DELETED_SUCCESS"
    NOTE_RETRIEVED_SUCCESS = "NOTE_RETRIEVED_SUCCESS"
    NOTES_LIST_RETRIEVED_SUCCESS = "NOTES_LIST_RETRIEVED_SUCCESS"
    NOTE_CATEGORIES_RETRIEVED_SUCCESS = "NOTE_CATEGORIES_RETRIEVED_SUCCESS"
    NOTE_PRIORITIES_RETRIEVED_SUCCESS = "NOTE_PRIORITIES_RETRIEVED_SUCCESS"
    
    # Transcription related
    TRANSCRIPTION_SERVICE_UNAVAILABLE = "TRANSCRIPTION_SERVICE_UNAVAILABLE"
    TRANSCRIPTION_FAILED = "TRANSCRIPTION_FAILED"
    TRANSCRIPTION_SAVE_FAILED = "TRANSCRIPTION_SAVE_FAILED"
    TRANSCRIPTION_GCS_REQUIRED = "TRANSCRIPTION_GCS_REQUIRED"
    TRANSCRIPTION_GCS_FAILED = "TRANSCRIPTION_GCS_FAILED"
    TRANSCRIPTION_ALREADY_EXISTS = "TRANSCRIPTION_ALREADY_EXISTS"
    TRANSCRIPTION_COMPLETED_SUCCESS = "TRANSCRIPTION_COMPLETED_SUCCESS"
    TRANSCRIPTION_DELETED_SUCCESS = "TRANSCRIPTION_DELETED_SUCCESS"
    TRANSCRIPTION_CHECK_COMPLETED = "TRANSCRIPTION_CHECK_COMPLETED"
    
    # AI/Summary related
    SUMMARY_GENERATION_FAILED = "SUMMARY_GENERATION_FAILED"
    SUMMARY_CREATED_SUCCESS = "SUMMARY_CREATED_SUCCESS"
    
    # Semantic Search related
    SEMANTIC_SEARCH_COMPLETED = "SEMANTIC_SEARCH_COMPLETED"
    
    # Google Cloud API related
    GOOGLE_CLOUD_API_ERROR = "GOOGLE_CLOUD_API_ERROR"
    
    # Auth related
    USER_REGISTERED_SUCCESS = "USER_REGISTERED_SUCCESS"
    LOGIN_SUCCESS = "LOGIN_SUCCESS"
    TOKEN_REFRESHED_SUCCESS = "TOKEN_REFRESHED_SUCCESS"
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS"
    USER_INFO_RETRIEVED_SUCCESS = "USER_INFO_RETRIEVED_SUCCESS"
    
    # Health check
    HEALTH_CHECK_COMPLETED = "HEALTH_CHECK_COMPLETED"
