"""add_embedding_columns_to_notes

Revision ID: 64837bfe8eef
Revises: 6f9e5630c6b5
Create Date: 2025-12-01 14:35:43.385198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '64837bfe8eef'
down_revision: Union[str, Sequence[str], None] = '6f9e5630c6b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('content_embedding', Vector(768), nullable=True))
    op.add_column('notes', sa.Column('summary_embedding', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'summary_embedding')
    op.drop_column('notes', 'content_embedding')
    # ### end Alembic commands ###
